/** Signal Atelier: an asymmetric data runway balances an editorial hero with crisp, actionable AI entry points. */
import { ArrowDownRight, ArrowUpRight, BadgeCheck, CircleDollarSign, Dumbbell, Gauge, Globe2, Leaf, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Link } from "wouter";
import ModelExplorer from "@/components/ModelExplorer";
import SiteShell from "@/components/SiteShell";
import { TOOLS } from "@/lib/catalog";

const iconBySlug = { "language-tutor": Globe2, "live-translation": Zap, "tarot-master": Sparkles, "gemini-quota": Gauge, "amazon-research": CircleDollarSign, "nutritionist": Leaf, "fitness-coach": Dumbbell } as const;
const heroImage = "/manus-storage/gugopro-hero-signal-atlas_4f0828f8.png";
const toolImage = "/manus-storage/gugopro-app-tool-network_dccd2674.png";
const modelImage = "/manus-storage/gugopro-model-explorer-constellation_55c556a2.png";

export default function Home() {
  return <SiteShell><main>
    <section className="hero-section"><div className="hero-art" style={{ backgroundImage: `url(${heroImage})` }} aria-hidden="true" /><div className="hero-grid-lines" aria-hidden="true" /><div className="hero-copy"><div className="hero-index"><span>GGP / 2026</span><i /><span>AI UTILITY ATLAS</span></div><p className="eyebrow hero-eyebrow"><span className="signal-dot" />GU-GO-PRO · AI FLAGSHIP CENTER</p><h1>把 AI 的<br /><em>可能性，</em><br />調到可用。</h1><p className="hero-lead">七個真正能開始工作的 AI 應用，一個能讀懂上下文、能力與成本的大模型入口。所有 Gemini 金鑰操作，皆在你的瀏覽器完成。</p><div className="hero-actions"><a href="#apps" className="signal-button">探索七大 AI 應用 <ArrowDownRight size={17} /></a><a href="#models" className="quiet-button">比較模型成本 <ArrowDownRight size={17} /></a></div></div><aside className="hero-readout"><div className="readout-top"><span>LIVE WORKSPACE</span><span className="pulse-label"><i /> LOCAL FIRST</span></div><div className="readout-stat"><strong>07</strong><span>整合 AI 工具<br />從對話到決策</span></div><div className="readout-stat compact"><strong>5+</strong><span>主流模型供應商<br />可比較資料</span></div><div className="readout-rule" /><p><ShieldCheck size={16} /> Key 不上傳。<br />請求由瀏覽器直連。</p></aside></section>
    <section className="ticker-bar" aria-label="GuGoPro 平台特點"><div><span>GUGOPRO SIGNAL</span><i /><span>LOCAL API KEY STORAGE</span><i /><span>MODEL COST ESTIMATOR</span><i /><span>SEVEN AI WORKSPACES</span><i /><span>TRANSPARENT LIMITS</span></div></section>
    <section id="apps" className="page-section tools-section" aria-labelledby="apps-title"><div className="section-kicker"><span>01</span><span>CORE APPLICATIONS</span><span className="line" /></div><div className="tools-heading"><div><h2 id="apps-title">不是展示用卡片。<br /><em>是可開始的工作區。</em></h2><p>為不同場景設計的七個 AI 入口，共用一套本機 Gemini API Key 設定，並在每個工具中標示出輸出邊界。</p></div><div className="tools-visual" style={{ backgroundImage: `url(${toolImage})` }}><span>07 MODULES</span></div></div><div className="tool-runway">{TOOLS.map((tool) => { const Icon = iconBySlug[tool.slug]; return <Link key={tool.slug} href={`/tools/${tool.slug}`} className="tool-card"><div className="tool-card-top"><span>{tool.index}</span><Icon size={21} /></div><p className="tool-category">{tool.category}</p><h3>{tool.shortTitle}</h3><p className="tool-description">{tool.description}</p><div className="tool-card-action">進入工作區 <ArrowUpRight size={16} /></div></Link>; })}</div></section>
    <section className="model-visual-band"><div className="model-visual-copy"><p className="eyebrow">MODEL INTELLIGENCE LAYER</p><h2>從看見模型，<br />到選對模型。</h2><p>即時篩選、成本換算、能力檢視。把 API 方案的關鍵資訊從分散頁面拉回同一張工作桌。</p><a href="#models" className="quiet-button">前往 Model Explorer <ArrowDownRight size={16} /></a></div><div className="model-visual-art" style={{ backgroundImage: `url(${modelImage})` }} /></section>
    <ModelExplorer />
    <section id="security" className="security-section"><div className="security-index"><span>03</span><span>PRIVACY BY ARCHITECTURE</span></div><div className="security-content"><div><p className="eyebrow"><ShieldCheck size={15} /> YOUR KEY, YOUR BROWSER</p><h2>你輸入的 Key，<em>不應該繞道。</em></h2></div><div className="security-copy"><p>GuGoPro 不設置代轉 API 的中繼伺服器。當你使用 Gemini 功能時，請求從你的裝置直接送往 Google；金鑰透過統一的 LocalStorage 名稱讀取，且可隨時在導覽列一鍵清除。</p><div className="security-points"><span><BadgeCheck size={17} />不硬編碼私有金鑰</span><span><BadgeCheck size={17} />不傳送至 GuGoPro 伺服器</span><span><BadgeCheck size={17} />本機可清除請求紀錄</span></div></div></div></section>
    <section className="closing-section"><div><p className="eyebrow">BUILD WITH CLARITY</p><h2>有選擇，<br /><em>才有更好的 AI。</em></h2></div><p>從第一個指令到下一個產品決策，GuGoPro 讓工具、模型與限制都保持在可見範圍。</p><a href="#apps" className="round-arrow" aria-label="回到 AI 應用區"><ArrowUpRight size={25} /></a></section>
  </main></SiteShell>;
}
