/** Signal Atelier: each AI workspace exposes one clear action, visible security boundaries, and measured output. */
import { useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, ArrowUpRight, Bot, CheckCircle2, Copy, Gauge, LoaderCircle, LockKeyhole, Send, ShieldCheck, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import SiteShell from "@/components/SiteShell";
import { getTool } from "@/lib/catalog";
import { useApiKey } from "@/contexts/ApiKeyContext";

type LogItem = { time: string; tool: string; status: "成功" | "失敗"; duration: number; };
const LOG_KEY = "gugopro_request_log";
const iconBySlug = { "language-tutor": Bot, "live-translation": Send, "tarot-master": Sparkles, "gemini-quota": Gauge, "amazon-research": Activity, "nutritionist": ShieldCheck, "fitness-coach": Activity } as const;
const appendLog = (item: LogItem) => { try { const existing = JSON.parse(localStorage.getItem(LOG_KEY) ?? "[]") as LogItem[]; localStorage.setItem(LOG_KEY, JSON.stringify([item, ...existing].slice(0, 20))); } catch { localStorage.setItem(LOG_KEY, JSON.stringify([item])); } };
const getLogs = () => { try { return JSON.parse(localStorage.getItem(LOG_KEY) ?? "[]") as LogItem[]; } catch { return [] as LogItem[]; } };

export default function ToolDetail() {
  const [, params] = useRoute("/tools/:slug"); const tool = getTool(params?.slug ?? ""); const { apiKey, hasApiKey } = useApiKey();
  const [input, setInput] = useState(""); const [language, setLanguage] = useState("繁體中文 → 英文"); const [spread, setSpread] = useState("三張牌：過去 / 現在 / 可能方向"); const [result, setResult] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [logs, setLogs] = useState<LogItem[]>(getLogs);
  const Icon = tool ? iconBySlug[tool.slug] : Bot; const isQuota = tool?.slug === "gemini-quota"; const canRun = Boolean(input.trim()) && hasApiKey && !loading; const workspaceTitle = useMemo(() => isQuota ? "連線與用量檢測" : "開始本機 AI 工作階段", [isQuota]);
  if (!tool) return <SiteShell><main className="not-found-panel"><h1>找不到此 AI 工作區。</h1><Link href="/" className="signal-button">回到 GuGoPro</Link></main></SiteShell>;
  const log = (status: "成功" | "失敗", started: number) => { appendLog({ time: new Date().toLocaleString("zh-TW"), tool: tool.shortTitle, status, duration: Math.round(performance.now() - started) }); setLogs(getLogs()); };
  const runWorkspace = async () => {
    if (!hasApiKey) { setError("請先在右上角設定 Gemini API Key。金鑰只會儲存於此瀏覽器。 "); return; }
    setLoading(true); setResult(""); setError(""); const started = performance.now();
    try {
      if (isQuota) {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(apiKey)}`); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "Gemini API 連線失敗"); const count = Array.isArray(data?.models) ? data.models.length : 0; log("成功", started); setResult(`API Key 目前可向 Gemini Generative Language API 發出請求。\n\n此金鑰可讀取 ${count} 個模型資訊。\n\n重要說明：Google 並未在此瀏覽器端點公開「每個 API Key 的剩餘日額度、實際速率限制或完整後台呼叫紀錄」。本頁顯示的是 GuGoPro 在此瀏覽器建立的本機請求紀錄；正式用量與配額請以 Google AI Studio 或 Google Cloud 專案後台為準。`);
      } else {
        const configuration = tool.slug === "live-translation" ? `\n翻譯方向：${language}` : tool.slug === "tarot-master" ? `\n牌陣偏好：${spread}` : ""; const prompt = `${tool.promptLead}${configuration}\n\n使用者輸入：\n${input}`;
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${encodeURIComponent(apiKey)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: prompt }] }], generationConfig: { temperature: 0.55, maxOutputTokens: 1500 } }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message ?? "Gemini API 連線失敗"); const text = data?.candidates?.[0]?.content?.parts?.map((part: { text?: string }) => part.text ?? "").join("\n") ?? "模型未回傳可顯示的文字內容。"; log("成功", started); setResult(text);
      }
    } catch (caught) { log("失敗", started); setError(caught instanceof Error ? caught.message : "無法完成此請求。請檢查 API Key 與網路連線。 "); } finally { setLoading(false); }
  };
  return <SiteShell><main className="tool-page">
    <div className="tool-hero-grid"><section><Link href="/" className="back-link"><ArrowLeft size={16} /> 返回 AI Hub</Link><div className="tool-number"><span>{tool.index}</span><i /></div><p className="eyebrow">{tool.category.toUpperCase()}</p><h1>{tool.title}</h1><p className="tool-lead">{tool.description}</p><div className="privacy-statement"><LockKeyhole size={17} /><span>請求從你的瀏覽器直接發往 Google；不經 GuGoPro 伺服器，也不會傳送或記錄你的 API Key。</span></div><a className="legacy-link" href={tool.legacyUrl} target="_blank" rel="noreferrer">開啟既有 GuGoPro 工具頁 <ArrowUpRight size={14} /></a></section><div className="tool-orbit"><div className="orbit-core"><Icon size={40} /></div><span className="orbit o1" /><span className="orbit o2" /><span className="orbit-node n1" /><span className="orbit-node n2" /><span className="orbit-node n3" /></div></div>
    <section className="workspace-section"><div className="workspace-heading"><div><p className="eyebrow">BROWSER-LOCAL WORKSPACE</p><h2>{workspaceTitle}</h2></div><span className={`local-chip ${hasApiKey ? "ready" : ""}`}><i />{hasApiKey ? "金鑰已在本機就緒" : "尚未設定本機金鑰"}</span></div><div className="workspace-grid"><div className="input-instrument">{isQuota ? <div className="quota-intro"><Gauge size={32} /><h3>以最少資料驗證連線</h3><p>按下檢測後，瀏覽器會使用你的金鑰呼叫 Gemini 模型清單端點。本頁不會傳送提示詞或儲存金鑰。可用模型數量與請求時間將寫入此瀏覽器的本機紀錄。</p></div> : <>{tool.slug === "live-translation" && <label className="field-label">翻譯方向<select className="field-input compact" value={language} onChange={(event) => setLanguage(event.target.value)}>{["繁體中文 → 英文", "英文 → 繁體中文", "繁體中文 → 日文", "日文 → 繁體中文", "繁體中文 → 韓文"].map((item) => <option key={item}>{item}</option>)}</select></label>}{tool.slug === "tarot-master" && <label className="field-label">牌陣選擇<select className="field-input compact" value={spread} onChange={(event) => setSpread(event.target.value)}>{["單張牌：聚焦此刻", "三張牌：過去 / 現在 / 可能方向", "五張牌：議題拆解與反思"].map((item) => <option key={item}>{item}</option>)}</select></label>}<label className="field-label" htmlFor="workspace-input">你的需求或背景</label><textarea id="workspace-input" className="workspace-textarea" value={input} onChange={(event) => setInput(event.target.value)} placeholder={tool.promptHint} rows={9} /></>}{tool.safetyNote && <div className="safety-note"><AlertTriangle size={16} /><span>{tool.safetyNote}</span></div>}<button className="signal-button wide" disabled={!isQuota && !canRun} onClick={() => void runWorkspace()}>{loading ? <LoaderCircle size={17} className="spin" /> : <Send size={17} />}{loading ? "正在向 Gemini 發出本機請求" : isQuota ? "執行連線檢測" : "送出至 Gemini"}</button>{!hasApiKey && <p className="key-reminder">尚未設定 API Key。請使用頁首的「設定 AI API Key」將金鑰保留在自己的瀏覽器。</p>}</div><div className="output-instrument"><div className="output-topline"><span>AI OUTPUT</span>{result && <button onClick={() => void navigator.clipboard?.writeText(result)}><Copy size={14} /> 複製</button>}</div>{loading ? <div className="output-empty"><LoaderCircle className="spin" size={26} /><p>等待 Gemini 回覆中…</p></div> : error ? <div className="output-error"><AlertTriangle size={23} /><p>{error}</p></div> : result ? <div className="result-text">{result}</div> : <div className="output-empty"><CheckCircle2 size={26} /><p>結果將顯示在這裡。<br />請先確認你的本機 API Key 狀態。</p></div>}</div></div></section>
    {isQuota && <section className="local-log-section"><div><p className="eyebrow">LOCAL REQUEST LOG</p><h2>此瀏覽器的呼叫紀錄</h2><p>只保存工具名稱、時間、結果與耗時，不保存 API Key、提示詞或模型回覆。清除瀏覽器網站資料即可移除。</p></div><div className="request-log">{logs.length ? logs.map((item, index) => <div key={`${item.time}-${index}`}><span className={item.status === "成功" ? "log-good" : "log-bad"}>{item.status}</span><strong>{item.tool}</strong><time>{item.time}</time><em>{item.duration} ms</em></div>) : <p>尚無本機紀錄。</p>}</div></section>}
  </main></SiteShell>;
}
