from pathlib import Path
from bs4 import BeautifulSoup
from collections import Counter
import re

ROOT = Path(__file__).resolve().parents[1]
AI_RE = re.compile(r"/tools/ai(?:/|-)|/tools/ai-media/|/tools/health/(?:tdee-macros-calculator|weight-loss-planner)(?:\.html)?", re.I)
LANG_NAMES = {
    "English": "en",
    "繁體中文": "zh-TW",
    "繁中": "zh-TW",
    "日本語": "ja",
    "Deutsch": "de",
    "Français": "fr",
    "Español": "es",
    "Português": "pt",
    "简体中文": "zh-CN",
}
INTERFACE_IDS = {"interface-lang", "ui-lang-toggle", "locale-select", "language"}
FUNCTIONAL_ID_RE = re.compile(r"(?:my-lang|target-lang|word-lookup-lang|study-language|partner-lang|self-lang|pdf-preset-translate-language)$", re.I)


def page_kind(path: Path) -> str:
    return "AI" if AI_RE.search("/" + path.as_posix()) else "Non-AI"


def text_langs(text: str) -> list[str]:
    return sorted({code for label, code in LANG_NAMES.items() if label in text})


def describe(path: Path) -> dict:
    source = path.read_text(encoding="utf-8", errors="ignore")
    soup = BeautifulSoup(source, "html.parser")
    interface = []
    functional = []
    for node in soup.select(".converter-language-link"):
        interface.append("standalone-language-link")
    for node in soup.select(".lang-dropdown, .lang-btn"):
        interface.append(node.get("class", ["legacy-language-control"])[0])
    for node in soup.select(".lang-selector"):
        if node.name == "select" or FUNCTIONAL_ID_RE.search(node.get("id", "")):
            functional.append("functional-select:" + (node.get("id") or "lang-selector"))
        else:
            interface.append("lang-selector")
    for node in soup.select("select"):
        node_id = node.get("id", "")
        if node_id in {"gugo-locale-select", "gugo-static-locale-select"}:
            continue
        if node_id in INTERFACE_IDS:
            interface.append("interface-select:" + node_id)
        elif FUNCTIONAL_ID_RE.search(node_id):
            label = "functional-select:" + node_id
            if label not in functional:
                functional.append(label)
    runtimes = []
    if "gugopro-i18n.js" in source:
        runtimes.append("gugopro-i18n.js")
    if "static-locale-runtime" in source:
        runtimes.append("static-locale-runtime")
    if "gugo-i18n-boot" in source:
        runtimes.append("i18n-boot")
    dynamic = []
    if "createElement('select')" in source or 'createElement("select")' in source:
        dynamic.append("dynamic-select")
    if "SUPPORTED_LOCALES" in source or "I18N =" in source or "const I18N" in source:
        dynamic.append("custom-catalog")
    if "localStorage" in source and re.search(r"lang|locale", source, re.I):
        dynamic.append("localStorage-locale")
    interface_count = len(interface)
    runtime_count = 1 if "gugopro-i18n.js" in source and page_kind(path) == "Non-AI" else 0
    estimated = interface_count + runtime_count
    return {
        "path": str(path.relative_to(ROOT)),
        "kind": page_kind(path),
        "interface_controls": interface_count,
        "functional_inputs": len(functional),
        "runtime_controls": runtime_count,
        "estimated_controls": estimated,
        "interface_sources": ", ".join(interface) or "—",
        "functional_sources": ", ".join(functional) or "—",
        "runtime_sources": ", ".join(runtimes) or "—",
        "dynamic_sources": ", ".join(dynamic) or "—",
        "languages": ", ".join(text_langs(source)) or "—",
        "duplicate": "YES" if estimated > 1 else "—",
    }


pages = [p for p in sorted(ROOT.rglob("*.html")) if ".git" not in p.parts]
rows = [describe(p) for p in pages]
counts = Counter((r["kind"], r["estimated_controls"]) for r in rows)

out = ROOT / "docs" / "language-control-audit.md"
with out.open("w", encoding="utf-8") as fh:
    fh.write("# Site-wide language-control audit\n\n")
    fh.write("Generated by `scripts/audit_language_controls.py` from the current Git `main` working tree after cleanup. **Interface controls** are locale selectors or legacy language menus; **functional language inputs** are tool settings such as speech pair, lookup, study, or translation target. Non-AI runtime controls count the shared `gugopro-i18n.js` selector. The historical pre-cleanup report is preserved in `docs/language-control-audit-baseline.md`.\n\n")
    fh.write("## Summary\n\n")
    fh.write(f"- HTML pages scanned: **{len(rows)}**\n")
    fh.write(f"- Pages with more than one interface control: **{sum(r['duplicate'] == 'YES' for r in rows)}**\n")
    fh.write(f"- Non-AI pages: **{sum(r['kind'] == 'Non-AI' for r in rows)}**\n")
    fh.write(f"- AI pages: **{sum(r['kind'] == 'AI' for r in rows)}**\n\n")
    fh.write("### Interface-control distribution\n\n")
    fh.write("| Page family | Interface controls | Pages |\n|---|---:|---:|\n")
    interface_counts = Counter((r["kind"], r["estimated_controls"]) for r in rows)
    for (kind, controls), total in sorted(interface_counts.items()):
        fh.write(f"| {kind} | {controls} | {total} |\n")
    fh.write("\n## Root causes addressed\n\n")
    fh.write("1. Converter Hub pages previously combined a static `.converter-language-link` English/Chinese anchor with the shared runtime selector. The static anchors are removed at source.\n")
    fh.write("2. Legacy finance pages previously contained `.lang-selector` / `.lang-dropdown` / `.lang-btn` menus, including pages with multiple hosts. Those hosts are removed at source; the runtime now reconciles any late-added legacy controls.\n")
    fh.write("3. Fifty-seven pages previously loaded the obsolete `static-locale-runtime.js` in addition to the shared runtime. Its tags and file are removed.\n")
    fh.write("4. AI pages retain catalog-backed interface or functional language controls. AI-owned health pages are detached from the generic Non-AI runtime, and the tutor's unfinished interface-language selector is removed rather than advertising untranslated UI.\n")
    fh.write("5. The shared runtime now follows URL query, localStorage, navigator language, then default; `navigator.language` no longer overrides an explicit user choice.\n\n")
    fh.write("## Page inventory\n\n")
    fh.write("| Page | Family | Interface sources | Functional language inputs | Runtime sources | Dynamic sources | Languages found | Interface controls | Duplicate |\n|---|---|---|---|---|---|---|---:|---|\n")
    for r in rows:
        fh.write("| {path} | {kind} | {interface_sources} | {functional_sources} | {runtime_sources} | {dynamic_sources} | {languages} | {estimated_controls} | {duplicate} |\n".format(**r))

print(f"scanned {len(rows)} HTML pages")
print(f"pages with >1 interface control: {sum(r['duplicate'] == 'YES' for r in rows)}")
print(f"wrote {out}")
for (kind, controls), total in sorted(counts.items()):
    print(f"{kind}\tcontrols={controls}\tpages={total}")
