from pathlib import Path

ROOT = Path('/home/ubuntu/gugopro-site')
ACADEMY = ROOT / 'academy'
TOOLS = ACADEMY / 'tools'

BASE = '''<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}｜GugoPro Academy</title><meta name="description" content="GugoPro Academy 互動式財經教育工具：用情境、公式與敏感度理解投資決策。"><link rel="stylesheet" href="../academy.css"></head>
<body><header class="topbar"><div class="shell nav"><a class="brand" href="../index.html"><span class="brandmark">G</span><span>GugoPro <em>Academy</em></span></a><nav class="navlinks"><a href="../index.html#curriculum">課程路徑</a><a href="../index.html#tools">互動工具</a><button class="theme-btn" data-theme aria-label="切換深色模式">◐</button></nav></div></header>
<main class="tool-page"><a class="back" href="../index.html#tools">← 返回互動工具實驗室</a><div class="tool-layout"><section class="panel"><span class="tag">{category}</span><h1>{title}</h1><p>{intro}</p>{fields}<button class="calc" id="calc">更新計算</button><p class="note">本工具只在瀏覽器計算，不會上傳輸入值。結果是教育示範，不構成投資建議。</p></section><section class="result"><div class="eyebrow">Decision dashboard</div><h2>{result_heading}</h2>{result_body}</section></div></main><footer class="footer"><div class="shell"><strong>GugoPro Academy</strong> · 以框架取代預測，以紀律管理不確定性。</div></footer><script src="../academy.js"></script><script>{script}</script></body></html>'''

pages = {
'asset-allocation.html': dict(title='資產配置壓力測試', category='組合 / IPS', intro='輸入你的目標權重與組合總額，快速看見再平衡時各資產需要增加或減少多少。', fields='''<label for="total">組合總額（NT$）</label><input id="total" type="number" value="1000000" min="0"><label for="eq">股票目標權重（%）</label><input id="eq" type="number" value="60" min="0" max="100"><label for="bd">債券目標權重（%）</label><input id="bd" type="number" value="30" min="0" max="100"><label for="cash">現金目標權重（%）</label><input id="cash" type="number" value="10" min="0" max="100"><label for="eqc">目前股票金額（NT$）</label><input id="eqc" type="number" value="520000" min="0"><label for="bdc">目前債券金額（NT$）</label><input id="bdc" type="number" value="320000" min="0">''', result_heading='偏離與行動建議', result_body='''<div class="metric-grid"><div class="metric"><small>目前股票</small><b id="eqr">—</b></div><div class="metric"><small>目前債券</small><b id="bdr">—</b></div><div class="metric"><small>目前現金</small><b id="cashr">—</b></div></div><div id="allocationRows" class="insight-list"></div><div class="callout compact"><p><strong>閱讀方式：</strong>再平衡不是追逐短期漲跌，而是把組合拉回預先寫下的風險預算。實務上可搭配現金流與容許偏離區間，降低不必要交易。</p></div>''', script='''const n=id=>Number(document.getElementById(id).value)||0; function money(v){return 'NT$ '+Math.round(v).toLocaleString('zh-TW')} function run(){const total=n('total'), targets=[['股票',n('eq'),n('eqc')],['債券',n('bd'),n('bdc')]];const cash=Math.max(total-targets[0][2]-targets[1][2],0), cashTarget=n('cash');document.getElementById('eqr').textContent=total?Math.round(targets[0][2]/total*100)+'%':'—';document.getElementById('bdr').textContent=total?Math.round(targets[1][2]/total*100)+'%':'—';document.getElementById('cashr').textContent=total?Math.round(cash/total*100)+'%':'—';document.getElementById('allocationRows').innerHTML=targets.concat([['現金',cashTarget,cash]]).map(([name,t,current])=>{const desired=total*t/100, delta=desired-current;return `<div class="insight-row"><span><strong>${name}</strong><small>目標 ${t}% · 目前 ${total?Math.round(current/total*100):0}%</small></span><b class="${delta>=0?'positive':'negative'}">${delta>=0?'增加':'減少'} ${money(Math.abs(delta))}</b></div>`}).join('')} document.getElementById('calc').onclick=run;run();'''),
'bond-duration.html': dict(title='債券久期敏感度', category='債券 / 利率', intro='用修正久期估算殖利率變動對債券價格的初步影響，建立利率風險的直覺。', fields='''<label for="price">債券價格（% of par）</label><input id="price" type="number" value="100" min="0"><label for="duration">修正久期（年）</label><input id="duration" type="number" value="6.5" min="0"><label for="change">殖利率變動（百分點）</label><input id="change" type="number" value="1" step="0.1"><label for="convexity">凸性（可選）</label><input id="convexity" type="number" value="45" min="0">''', result_heading='價格變動估算', result_body='''<div class="result-big" id="impact">—</div><div class="metric-grid"><div class="metric"><small>估算後價格</small><b id="newPrice">—</b></div><div class="metric"><small>久期效果</small><b id="durationEffect">—</b></div><div class="metric"><small>凸性修正</small><b id="convexityEffect">—</b></div></div><div class="callout compact"><p><strong>重要限制：</strong>久期是局部近似，實際價格還會受信用利差、流動性、票息與殖利率曲線形狀影響。利率上升通常使價格下跌，但不是所有債券的風險相同。</p></div>''', script='''const n=id=>Number(document.getElementById(id).value)||0;function run(){const p=n('price'),d=n('duration'),y=n('change')/100,c=n('convexity'),linear=-d*y,convex=.5*c*y*y,total=linear+convex;document.getElementById('impact').textContent=(total*100).toFixed(2)+'%';document.getElementById('newPrice').textContent=(p*(1+total)).toFixed(2);document.getElementById('durationEffect').textContent=(linear*100).toFixed(2)+'%';document.getElementById('convexityEffect').textContent='+'+(convex*100).toFixed(2)+'%'}document.getElementById('calc').onclick=run;run();'''),
'savings-rate.html': dict(title='儲蓄率與目標路徑', category='個人財務 / 目標', intro='先把收入、支出與既有資產放在同一張表，估算達成資產目標所需的時間與敏感度。', fields='''<label for="income">每月可支配收入（NT$）</label><input id="income" type="number" value="80000" min="0"><label for="expense">每月必要支出（NT$）</label><input id="expense" type="number" value="50000" min="0"><label for="asset">目前可投資資產（NT$）</label><input id="asset" type="number" value="500000" min="0"><label for="target">資產目標（NT$）</label><input id="target" type="number" value="5000000" min="0"><label for="return">假設年化報酬（%）</label><input id="return" type="number" value="5" step="0.5">''', result_heading='目標路徑估算', result_body='''<div class="result-big" id="years">—</div><div class="metric-grid"><div class="metric"><small>每月儲蓄</small><b id="saving">—</b></div><div class="metric"><small>儲蓄率</small><b id="rate">—</b></div><div class="metric"><small>不含報酬所需</small><b id="simpleYears">—</b></div></div><div class="callout compact"><p><strong>閱讀方式：</strong>報酬率只是模型假設；提高儲蓄率、控制固定支出與延長時間，往往比追求更高風險的報酬更可控。請以多個情境檢查結果。</p></div>''', script='''const n=id=>Number(document.getElementById(id).value)||0;function run(){const income=n('income'),expense=n('expense'),asset=n('asset'),target=n('target'),r=n('return')/100/12,saving=Math.max(income-expense,0);document.getElementById('saving').textContent='NT$ '+Math.round(saving).toLocaleString('zh-TW');document.getElementById('rate').textContent=income?(saving/income*100).toFixed(1)+'%':'—';let months=0,b=asset;while(b<target&&months<1200){b=b*(1+r)+saving;months++}document.getElementById('years').textContent=months<1200?(months/12).toFixed(1)+' 年':'超過 100 年';document.getElementById('simpleYears').textContent=saving?((Math.max(target-asset,0)/saving)/12).toFixed(1)+' 年':'無法估算'}document.getElementById('calc').onclick=run;run();''')}

for filename, data in pages.items():
    html = BASE
    for key, value in data.items():
        html = html.replace('{' + key + '}', value)
    (TOOLS / filename).write_text(html, encoding='utf-8')

index = (ACADEMY / 'index.html').read_text(encoding='utf-8')
needle = '<div class="tool"><small>08 / 防守</small>'
insert = '<div class="tool"><small>09 / 配置</small><h3>資產配置壓力測試</h3><a href="tools/asset-allocation.html">看見偏離金額 →</a></div><div class="tool"><small>10 / 債券</small><h3>債券久期敏感度</h3><a href="tools/bond-duration.html">估算利率衝擊 →</a></div><div class="tool"><small>11 / 目標</small><h3>儲蓄率與目標路徑</h3><a href="tools/savings-rate.html">估算達標時間 →</a></div>'
if 'asset-allocation.html' not in index:
    index = index.replace(needle, insert + needle)
resources = '''<section class="section sources" id="sources"><div class="sectionhead"><div><div class="eyebrow">Research desk</div><h2>把學習連到可驗證的框架</h2><p class="lead">課程不鼓勵用單一指標預測市場，而是練習把目標、時間、風險承受度與證據寫清楚。以下外部資源可作為延伸閱讀。</p></div></div><div class="source-grid"><a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation" target="_blank" rel="noopener"><strong>Asset allocation & diversification</strong><span>Investor.gov：配置、分散與投資期限</span></a><a href="https://www.finra.org/investors/insights/know-your-risk-tolerance" target="_blank" rel="noopener"><strong>Know your risk tolerance</strong><span>FINRA：風險承受度與承擔能力</span></a><a href="https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" target="_blank" rel="noopener"><strong>Compound interest</strong><span>Investor.gov：複利與時間價值</span></a></div></section>'''
if 'id="sources"' not in index:
    index = index.replace('<section class="section" id="method">', resources + '<section class="section" id="method">')
(ACADEMY / 'index.html').write_text(index, encoding='utf-8')

css = (ACADEMY / 'academy.css').read_text(encoding='utf-8')
css += '''\n/* Academy upgrade: decision-oriented cards, sources and tool feedback */\n.source-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.source-grid a{display:flex;flex-direction:column;gap:8px;padding:20px;background:var(--surface);border:1px solid var(--line);border-radius:16px;color:var(--ink);transition:transform .18s ease,box-shadow .18s ease}.source-grid a:hover{transform:translateY(-3px);box-shadow:var(--shadow)}.source-grid span{color:var(--muted);font-size:14px}.insight-list{display:grid;gap:10px;margin:24px 0}.insight-row{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:14px 16px;background:var(--soft);border-radius:12px}.insight-row span{display:flex;flex-direction:column;gap:4px}.insight-row small{color:var(--muted)}.positive{color:#087f5b}.negative{color:#c2410c}.compact{margin-top:24px;padding:16px}.compact p{margin:0}.result-big{letter-spacing:-.04em}.theme-btn{border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:9px;padding:7px 10px;cursor:pointer}.theme-btn:active,.calc:active,.btn:active{transform:scale(.97)}@media(max-width:850px){.source-grid{grid-template-columns:1fr}.insight-row{align-items:flex-start;flex-direction:column;gap:8px}}\n'''
(ACADEMY / 'academy.css').write_text(css, encoding='utf-8')

js = '''(()=>{const root=document.documentElement;const themeKey='gugopro_academy_theme';const progressKey='gugopro_academy_progress';let done=[];try{done=JSON.parse(localStorage.getItem(progressKey)||'[]')}catch(e){}if(localStorage.getItem(themeKey)==='dark')root.classList.add('dark');document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-theme]').forEach(toggle=>toggle.addEventListener('click',()=>{root.classList.toggle('dark');try{localStorage.setItem(themeKey,root.classList.contains('dark')?'dark':'light')}catch(e){}}));document.querySelectorAll('[data-lesson]').forEach(el=>{const id=el.dataset.lesson;if(done.includes(id))el.classList.add('is-done');el.addEventListener('click',()=>{if(!done.includes(id)){done=[...done,id];try{localStorage.setItem(progressKey,JSON.stringify(done))}catch(e){}el.classList.add('is-done')}})});const total=document.querySelectorAll('[data-lesson]').length;const finished=done.filter(id=>document.querySelector(`[data-lesson="${id}"]`)).length;const text=document.querySelector('[data-progress-text]');const bar=document.querySelector('[data-progress-bar]');if(text)text.textContent=`學習進度 ${finished} / ${total}`;if(bar)bar.style.width=(total?finished/total*100:0)+'%'});})();\n'''
(ACADEMY / 'academy.js').write_text(js, encoding='utf-8')
print('academy upgrade written:', ', '.join(pages))

