/** Signal Atelier: the explorer turns complex model metadata into a legible comparison instrument. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Calculator, CheckCircle2, DatabaseZap, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import { FALLBACK_MODELS, ModelRecord } from "@/lib/catalog";

type LiveModel = { name?: string; limit?: { context?: number }; cost?: { input?: number; output?: number }; modalities?: { input?: string[] }; reasoning?: boolean; };
const providerOrder = ["Google", "OpenAI", "Anthropic", "DeepSeek", "Meta"];
const resolveProvider = (key: string, name: string) => { const value = `${key} ${name}`.toLowerCase(); if (value.includes("google") || value.includes("gemini")) return "Google"; if (value.includes("openai") || value.includes("gpt")) return "OpenAI"; if (value.includes("anthropic") || value.includes("claude")) return "Anthropic"; if (value.includes("deepseek")) return "DeepSeek"; if (value.includes("meta") || value.includes("llama")) return "Meta"; return null; };
const formatContext = (tokens: number) => tokens >= 1_000_000 ? `${(tokens / 1_000_000).toFixed(tokens % 1_000_000 === 0 ? 0 : 1)}M` : `${Math.round(tokens / 1_000)}K`;
const formatCost = (cost: number | null) => cost === null || Number.isNaN(cost) ? "供應商定價" : `$${cost.toFixed(cost < 1 ? 3 : 2)}`;
const modalityDisplay = (modalities: string[]) => modalities.map((item) => ({ text: "文字", image: "視覺", audio: "音訊", video: "視訊", pdf: "文件" }[item.toLowerCase()] ?? (item.toLowerCase().includes("code") ? "代碼" : item))).slice(0, 4);

function normalizeLiveModels(payload: Record<string, { name?: string; models?: Record<string, LiveModel> }>) {
  const all: ModelRecord[] = [];
  Object.entries(payload).forEach(([providerKey, provider]) => Object.entries(provider.models ?? {}).forEach(([modelId, model]) => {
    const providerName = resolveProvider(providerKey, `${provider.name ?? ""} ${model.name ?? modelId}`); if (!providerName) return;
    all.push({ id: `${providerKey}-${modelId}`, name: model.name ?? modelId, provider: providerName, context: model.limit?.context ?? 0, input: typeof model.cost?.input === "number" ? model.cost.input : null, output: typeof model.cost?.output === "number" ? model.cost.output : null, modalities: model.modalities?.input ?? ["text"], reasoning: model.reasoning ? 90 : 72, source: "https://models.dev", sourceLabel: "models.dev" });
  }));
  return providerOrder.flatMap((provider) => all.filter((model) => model.provider === provider).slice(0, 14));
}

export default function ModelExplorer() {
  const [models, setModels] = useState<ModelRecord[]>(FALLBACK_MODELS); const [status, setStatus] = useState<"loading" | "live" | "fallback">("loading");
  const [query, setQuery] = useState(""); const [provider, setProvider] = useState("全部供應商"); const [modality, setModality] = useState("全部能力"); const [selectedId, setSelectedId] = useState(FALLBACK_MODELS[0].id); const [inputTokens, setInputTokens] = useState(100_000); const [outputTokens, setOutputTokens] = useState(20_000);
  const refreshModels = async () => { setStatus("loading"); try { const response = await fetch("https://models.dev/api.json", { cache: "no-store" }); if (!response.ok) throw new Error(); const live = normalizeLiveModels(await response.json() as Record<string, { name?: string; models?: Record<string, LiveModel> }>); if (live.length < 5) throw new Error(); setModels(live); setSelectedId(live[0].id); setStatus("live"); } catch { setModels(FALLBACK_MODELS); setSelectedId(FALLBACK_MODELS[0].id); setStatus("fallback"); } };
  useEffect(() => { void refreshModels(); }, []);
  const providers = useMemo(() => ["全部供應商", ...providerOrder.filter((name) => models.some((model) => model.provider === name))], [models]);
  const filtered = useMemo(() => models.filter((model) => { const needle = query.trim().toLowerCase(); return (!needle || `${model.name} ${model.provider}`.toLowerCase().includes(needle)) && (provider === "全部供應商" || model.provider === provider) && (modality === "全部能力" || modalityDisplay(model.modalities).includes(modality)); }), [models, modality, provider, query]);
  const selected = models.find((model) => model.id === selectedId) ?? models[0]; const estimate = selected && selected.input !== null && selected.output !== null ? (inputTokens / 1_000_000) * selected.input + (outputTokens / 1_000_000) * selected.output : null;

  return <section id="models" className="page-section explorer-section" aria-labelledby="models-title">
    <div className="section-kicker"><span>02</span><span>MODEL EXPLORER</span><span className="line" /></div>
    <div className="explorer-intro"><div><h2 id="models-title">把模型選擇，<em>變成可比較的決策。</em></h2><p>依模型名稱、供應商、上下文視窗、每百萬 Token 成本、多模態支援與 GuGo 推理指標篩選。資料會在你的瀏覽器嘗試直接向公開模型資料來源更新。</p></div><div className={`live-state ${status}`}><span className="state-dot" /><span>{status === "live" ? "即時資料已載入" : status === "loading" ? "正在同步公開資料" : "使用內建比較資料"}</span><button onClick={() => void refreshModels()} aria-label="重新更新模型資料"><RefreshCw size={15} className={status === "loading" ? "spin" : ""} /></button></div></div>
    <div className="explorer-grid"><div className="model-panel"><div className="filter-row"><label className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋模型或供應商" /></label><label className="select-box"><SlidersHorizontal size={15} /><select value={provider} onChange={(event) => setProvider(event.target.value)}>{providers.map((item) => <option key={item}>{item}</option>)}</select></label><label className="select-box"><select value={modality} onChange={(event) => setModality(event.target.value)}>{["全部能力", "視覺", "音訊", "代碼"].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="table-caption"><span>顯示 {filtered.length} 個模型</span><span>USD / 1M Tokens · 未含稅費</span></div><div className="model-table-wrap"><table className="model-table"><thead><tr><th>模型</th><th>Context</th><th>輸入</th><th>輸出</th><th>能力</th><th>推理</th></tr></thead><tbody>{filtered.slice(0, 12).map((model) => <tr key={model.id} className={selected?.id === model.id ? "active" : ""} onClick={() => setSelectedId(model.id)} tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter") setSelectedId(model.id); }}><td><strong>{model.name}</strong><span>{model.provider}</span></td><td className="mono">{model.context ? formatContext(model.context) : "—"}</td><td className="mono">{formatCost(model.input)}</td><td className="mono">{formatCost(model.output)}</td><td><div className="modality-list">{modalityDisplay(model.modalities).map((item) => <span key={item}>{item}</span>)}</div></td><td><div className="reasoning-score"><i style={{ width: `${model.reasoning}%` }} /><span>{model.reasoning}</span></div></td></tr>)}</tbody></table></div><div className="model-footnote"><DatabaseZap size={15} /><span>「GuGo 推理指標」是依公開能力訊號做的比較輔助，並非原廠基準測試。價格與可用性請在實作前點選原廠來源確認。</span></div></div>
      <aside className="calculator-panel" aria-labelledby="calculator-title"><div className="calc-icon"><Calculator size={22} /></div><p className="eyebrow">TOKEN COST ESTIMATOR</p><h3 id="calculator-title">一次調用，<br />先算清成本。</h3><label className="field-label" htmlFor="model-select">比較模型</label><select id="model-select" className="field-input" value={selected?.id ?? ""} onChange={(event) => setSelectedId(event.target.value)}>{models.map((model) => <option key={model.id} value={model.id}>{model.provider} · {model.name}</option>)}</select><div className="cost-inputs"><label><span>輸入 Tokens</span><input type="number" min="0" value={inputTokens} onChange={(event) => setInputTokens(Number(event.target.value))} /></label><label><span>輸出 Tokens</span><input type="number" min="0" value={outputTokens} onChange={(event) => setOutputTokens(Number(event.target.value))} /></label></div><div className="estimate-block"><span>預估 API 成本</span><strong>{estimate === null ? "請確認原廠定價" : `$${estimate.toFixed(4)}`}</strong><small>以輸入 {inputTokens.toLocaleString()} / 輸出 {outputTokens.toLocaleString()} Tokens 試算</small></div>{selected && <a className="source-link" href={selected.source} target="_blank" rel="noreferrer"><CheckCircle2 size={15} /> 查看 {selected.sourceLabel} 定價依據 <ArrowUpRight size={14} /></a>}</aside>
    </div>
  </section>;
}
