/* English localization layer for the browser-local Converter pages. */
(function () {
    'use strict';
    var C = window.ConverterCommon;
    if (!C) return;

    var pairs = [
        ['線上轉檔工具專區', 'Converter Hub'], ['線上Converter Hub Converter Hub', 'Online Converter Hub | GugoPro'],
        ['生活實用工具', 'Utility Tools'], ['轉檔工具', 'Converter Tools'], ['支持創作', 'Support the project'], ['主站首頁', 'Main site'], ['主站工具總覽', 'All site tools'],
        ['隱私權政策', 'Privacy Policy'], ['服務條款', 'Terms of Service'], ['喜歡這個工具？請在 Ko-fi 支持我們', 'Enjoy this tool? Support us on Ko-fi'], ['返回 Converter Hub', 'Back to Converter Hub'],
        ['字幕格式轉換器', 'Subtitle Converter'], ['多功能影像處理器', 'Image Converter'], ['結構化數據轉換器', 'Structured Data Converter'], ['圖片合併轉 PDF', 'Images to PDF'],
        ['Markdown 雙向轉換器', 'Markdown Converter'], ['Base64 / SVG 編解碼器', 'Base64 / SVG Codec'], ['音訊格式轉換器', 'Audio Converter'], ['色彩代碼轉換器', 'Color Converter'],
        ['字幕工作流', 'Subtitle workflow'], ['影像工作流', 'Image workflow'], ['資料工作流', 'Data workflow'], ['文件工作流', 'Document workflow'], ['開發工作流', 'Developer workflow'], ['音訊工作流', 'Audio workflow'], ['設計工作流', 'Design workflow'],
        ['字幕', 'Subtitles'], ['影像', 'Image'], ['數據', 'Data'], ['音訊', 'Audio'], ['色彩', 'Color'], ['圖片', 'Images'], ['本機', 'Local'], ['本地', 'Local'], ['本地處理', 'Local processing'], ['裝置本地運算', 'On-device processing'], ['瀏覽器本地運算', 'Browser-local processing'], ['不上傳', 'No uploads'], ['零伺服器上傳', 'Zero server uploads'], ['100% 本地安全運算', '100% local processing'], ['0 檔案上傳', '0 uploads'],
        ['開始選擇工具', 'Choose a tool'], ['了解隱私設計', 'Learn about privacy'], ['首波核心工具', 'Core tools'], ['8 合 1 旗艦工具套件', '8-in-1 flagship toolkit'], ['工具特色', 'Tool features'], ['為什麼選擇本地轉檔？', 'Why local conversion?'], ['拖曳檔案、即時預覽，所有轉換完成後一鍵下載。', 'Drop files, preview instantly and download every conversion with one click.'],
        ['檔案轉換，留在你的瀏覽器裡完成。', 'File conversion, completed in your browser.'], ['字幕、影像、資料、PDF、Markdown、Base64、音訊與色彩工具一次到位。所有內容都只在你的裝置上處理，不上傳、不等待伺服器，適合日常內容製作、設計與研究工作流。', 'Subtitles, images, data, PDF, Markdown, Base64, audio and color tools in one place. Everything is processed on your device with no uploads or server wait, ready for everyday creation, design and research workflows.'],
        ['Web APIs / Canvas 在你的瀏覽器執行', 'Web APIs / Canvas run in your browser'], ['不建立檔案上傳流程，不碰你的原始檔', 'No upload workflow is created and your originals are never touched'], ['完成後直接輸出 Blob，減少等待', 'Export a Blob directly when finished to reduce waiting'], ['手機、平板、桌面皆可操作', 'Works on phones, tablets and desktops'],
        ['檔案名稱', 'File name'], ['檔案大小', 'File size'], ['檔案類型', 'File type'], ['瀏覽器未標示', 'Not specified by browser'], ['處理進度', 'Processing progress'], ['輸出預覽', 'Output preview'], ['輸出摘要', 'Output summary'], ['清除', 'Clear'], ['下載最近輸出', 'Download latest output'],
        ['設定轉換參數', 'Set conversion options'], ['支援拖曳或點擊選擇單一字幕檔案。', 'Drop or click to choose one subtitle file.'], ['拖曳 SRT / VTT 到這裡', 'Drop an SRT / VTT file here'], ['或點擊選擇檔案', 'or click to choose a file'], ['只在你的瀏覽器處理', 'processed only in your browser'], ['輸出格式', 'Output format'], ['時間軸偏移（毫秒）', 'Timeline offset (ms)'], ['正值延後字幕，負值提前字幕。', 'Positive values delay subtitles; negative values move them earlier.'], ['自動判斷（SRT ⇄ VTT）', 'Auto-detect (SRT ⇄ VTT)'], ['輸出 SRT', 'Output SRT'], ['輸出 VTT', 'Output VTT'], ['轉換字幕', 'Convert subtitles'], ['只匯出 TXT 腳本', 'Export TXT script only'], ['返回 Converter Hub', 'Back to Converter Hub'], ['使用方式', 'How it works'], ['延遲微調', 'Delay adjustment'], ['隱私承諾', 'Privacy promise'], ['已移除時間戳，TXT 腳本可以下載。', 'Timestamps removed. Your TXT script is ready.'], ['字幕轉換完成，可以下載輸出檔。', 'Subtitle conversion complete. Your file is ready to download.'], ['請先選擇字幕檔案。', 'Choose a subtitle file to begin.'], ['請選擇 .srt 或 .vtt 字幕檔案。', 'Choose an .srt or .vtt subtitle file.'], ['正在於本機解析字幕內容…', 'Parsing subtitle content locally…'], ['已載入檔案，正在讀取內容…', 'File loaded. Reading content locally…'], ['檔案已準備好，請選擇輸出格式或匯出 TXT。', 'File ready. Choose an output format or export TXT.'], ['讀取檔案失敗，請重新選擇。', 'Could not read the file. Please choose it again.'], ['下載輸出檔', 'Download output'],
        ['影像設定與輸出', 'Image settings and export'], ['不必上傳到網站，直接在瀏覽器內完成格式轉換、壓縮、縮放、Favicon ICO 生成與 Base64 導出。', 'Convert, compress, resize, generate Favicon ICO files and export Base64 directly in your browser without uploading.'], ['拖曳影像到這裡', 'Drop an image here'], ['或點擊選擇圖片', 'or click to choose an image'], ['不上傳伺服器', 'No server upload'], ['原始影像預覽', 'Original image preview'], ['選擇圖片後會顯示尺寸與預覽。', 'Dimensions and a preview appear after you choose an image.'], ['WEBP（推薦）', 'WEBP (recommended)'], ['輸出寬度（px）', 'Output width (px)'], ['維持原尺寸', 'Keep original size'], ['品質：82%', 'Quality: 82%'], ['等比例縮放（建議保持勾選）', 'Keep aspect ratio (recommended)'], ['JPG / WEBP 會使用品質滑桿；PNG 以無損方式輸出。', 'JPG / WEBP use the quality slider; PNG is always lossless.'], ['轉換與壓縮', 'Convert and compress'], ['生成多尺寸 Favicon ICO', 'Generate multi-size Favicon ICO'], ['導出 Base64', 'Export Base64'], ['請先選擇圖片。', 'Choose an image to begin.'], ['參數小抄', 'Quick reference'], ['Favicon 輸出', 'Favicon export'], ['影像只經過本機 Image、Canvas 與 Blob API；原始檔不會離開你的裝置。', 'Images only pass through local Image, Canvas and Blob APIs; originals never leave your device.'], ['影像轉換完成，可以下載輸出檔。', 'Image conversion complete. Your file is ready to download.'], ['Favicon ICO 已生成，可以下載輸出檔。', 'Favicon ICO generated. Your file is ready to download.'], ['Base64 已準備完成，可以複製或下載。', 'Base64 is ready to copy or download.'], ['請選擇 PNG、JPG、JPEG 或 WEBP 圖片。', 'Choose a PNG, JPG, JPEG or WEBP image.'],
        ['匯入、預覽與匯出', 'Import, preview and export'], ['用 SheetJS 在本機解析 JSON、CSV 與 Excel XLSX，先預覽表格，再選擇想要的格式下載，不需要把資料送到雲端。', 'Use SheetJS to parse JSON, CSV and Excel XLSX locally, preview the table, then download the format you need without sending data to the cloud.'], ['支援 JSON 陣列 / 物件、CSV 與 XLSX / XLS。', 'Supports JSON arrays / objects, CSV and XLSX / XLS.'], ['拖曳 JSON / CSV / XLSX 到這裡', 'Drop JSON / CSV / XLSX here'], ['所有解析都在本地執行', 'All parsing runs locally'], ['工作表名稱（XLSX）', 'Sheet name (XLSX)'], ['表格預覽', 'Table preview'], ['選擇資料檔案後會顯示前 40 列預覽。', 'The first 40 rows appear after you choose a data file.'], ['匯出並下載', 'Export and download'], ['解析與匯出進度', 'Parse and export progress'], ['請先選擇 JSON、CSV 或 Excel 檔案。', 'Choose a JSON, CSV or Excel file to begin.'], ['資料整理提示', 'Data tips'], ['JSON 陣列會以物件鍵名建立欄位；若每列欄位不同，空白儲存格會自動補齊。', 'JSON arrays use object keys as columns; missing fields are filled with blank cells.'], ['預覽範圍', 'Preview scope'], ['介面預覽前 40 列、前 12 欄，完整資料仍會保留在下載檔案中。', 'The interface previews 40 rows and 12 columns; the full dataset remains in the download.'], ['SheetJS 只在目前頁面的 JavaScript 執行環境解析檔案，不會呼叫上傳端點。', 'SheetJS parses files only in this page’s JavaScript environment and never calls an upload endpoint.'], ['正在於本機解析資料…', 'Parsing data locally…'], ['解析完成：', 'Parsing complete: '], ['列，可以選擇輸出格式。', ' rows. Choose an output format.'], ['輸出完成，可以下載 ', 'Export complete. Download '], ['無法建立預覽。', 'Unable to create a preview.'], ['解析失敗：', 'Parsing failed: '], ['檔案格式不正確', 'invalid file format'], ['欄位 ', 'Column '], ['資料是空的，沒有可預覽的列。', 'The data is empty; there are no rows to preview.'], ['已建立 XLSX 工作簿：', 'XLSX workbook created: '], ['資料列數：', 'Rows: '], ['欄位數：', 'Columns: '],
        ['拖曳多張圖片到這裡', 'Drop multiple images here'], ['支援 PNG、JPG、WEBP', 'PNG, JPG and WEBP supported'], ['目前尚未加入圖片。', 'No images added yet.'], ['紙張', 'Paper size'], ['頁面方向', 'Orientation'], ['直式 Portrait', 'Portrait'], ['橫式 Landscape', 'Landscape'], ['頁邊距（mm）', 'Margin (mm)'], ['每張圖片會等比例縮放並置中於頁面內，不會裁切。', 'Each image is scaled proportionally and centered without cropping.'], ['合併並下載 PDF', 'Merge and download PDF'], ['清除全部', 'Clear all'], ['PDF 生成進度', 'PDF generation progress'], ['請先加入至少一張圖片。', 'Add at least one image to begin.'], ['調整順序', 'Reorder images'], ['每張圖片右側的上移、下移按鈕只會改變本地清單順序；你可以在生成前反覆調整。', 'The up/down buttons only change the local list order; adjust it as often as needed before generating.'], ['版面適配', 'Page fitting'], ['工具會依圖片比例自動縮放，保留頁邊距，不會把圖片送往外部服務。', 'The tool scales images to fit the page and margin without sending them to an external service.'], ['jsPDF 在目前頁面中建立 PDF Blob，原始影像不會離開你的裝置。', 'jsPDF creates the PDF Blob in this page; original images never leave your device.'], ['PDF 生成完成，可以下載輸出檔。', 'PDF generation complete. Your file is ready to download.'], ['請選擇 PNG、JPG 或 WEBP 圖片。', 'Choose a PNG, JPG or WEBP image.'],
        ['文字或 DataURI', 'Text or DataURI'], ['文字或圖片', 'Text or image'], ['編碼成 Base64', 'Encode as Base64'], ['解碼 Base64', 'Decode Base64'], ['複製結果', 'Copy result'], ['下載結果', 'Download result'], ['拖曳圖片到這裡取得 DataURI', 'Drop an image here to get a DataURI'], ['圖片只在你的瀏覽器讀取', 'Images are read only in your browser'], ['DataURI 預覽', 'DataURI preview'], ['SVG 即時預覽與優化', 'Live SVG preview and optimization'], ['移除註解、事件屬性與多餘空白，再複製或下載精簡後的 SVG。', 'Remove comments, event attributes and extra whitespace, then copy or download the optimized SVG.'], ['SVG 程式碼', 'SVG code'], ['預覽 SVG', 'Preview SVG'], ['壓縮優化', 'Optimize'], ['複製 SVG', 'Copy SVG'], ['下載 SVG', 'Download SVG'], ['請貼上內容或選擇圖片。', 'Paste content or choose an image.'], ['Base64 格式無法解碼，請確認內容完整。', 'Base64 could not be decoded. Check that the content is complete.'], ['圖片 DataURI 已準備完成。', 'Image DataURI is ready.'], ['SVG 格式無法解析，請檢查根元素。', 'SVG could not be parsed. Check the root element.'], ['SVG 已安全壓縮優化。', 'SVG safely optimized.'], ['SVG 預覽已更新。', 'SVG preview updated.'], ['沒有可複製的內容。', 'There is nothing to copy.'], ['請先輸入有效 SVG。', 'Enter valid SVG first.'], ['Base64 DataURI 工具', 'Base64 DataURI tools'], ['文字可做 UTF-8 編解碼；圖片則直接讀取為 data URI。', 'Encode or decode UTF-8 text; images are read directly as data URIs.'], ['所有內容只經過目前頁面的 File API、TextEncoder 與 DOMParser，不會上傳到伺服器。', 'Content uses only this page’s File API, TextEncoder and DOMParser; nothing is uploaded.'], ['文字編碼使用 UTF-8；輸入 data URI 解碼時會自動辨識文字或圖片 MIME type。', 'Text uses UTF-8 encoding; DataURI decoding detects text or image MIME types automatically.'], ['SVG 安全預覽', 'Safe SVG preview'], ['預覽會移除 script、foreignObject 與 on* 事件屬性，避免不必要的執行風險。', 'The preview removes scripts, foreignObject and on* attributes to avoid unnecessary execution risks.'],
        ['載入音訊並輸出', 'Load audio and export'], ['選擇格式與取樣率後，在目前裝置生成新的音訊檔。', 'Choose a format and sample rate to create a new audio file on this device.'], ['拖曳音訊到這裡', 'Drop audio here'], ['支援 WAV、MP3、OGG、M4A 等可由瀏覽器解碼的格式', 'Supports browser-decodable WAV, MP3, OGG, M4A and more'], ['輸出取樣率', 'Output sample rate'], ['保持原始取樣率', 'Keep original sample rate'], ['品質與檔案大小的平衡。', 'Balance sound quality and file size.'], ['Vorbis VBR 品質，數值越高音質越好。', 'Vorbis VBR quality; higher values sound better.'], ['轉換音訊', 'Convert audio'], ['格式說明', 'Format guide'], ['WAV 適合保留無損音質；MP3 適合較小的分享檔案；OGG Vorbis 適合開放格式與網頁音訊。', 'WAV preserves lossless quality; MP3 is compact for sharing; OGG Vorbis is an open format suited to web audio.'], ['取樣率壓縮', 'Sample-rate compression'], ['降低取樣率可以縮小檔案，但可能減少高頻細節；保持原始值則不進行重取樣。', 'Lower sample rates reduce file size but may remove high-frequency detail; keeping the original skips resampling.'], ['Web Audio API、lamejs 與 OggVorbisEncoder 都在目前瀏覽器執行，音訊不會離開你的裝置。', 'Web Audio API, lamejs and OggVorbisEncoder run in this browser; audio never leaves your device.'], ['請先選擇音訊檔案。', 'Choose an audio file to begin.'], ['正在使用 Web Audio API 解碼音訊…', 'Decoding audio with the Web Audio API…'], ['音訊已準備好，請選擇輸出設定。', 'Audio is ready. Choose output settings.'], ['無法解碼此音訊，請改用 WAV、MP3 或 OGG。', 'This audio could not be decoded. Try WAV, MP3 or OGG.'], ['瀏覽器不支援 Web Audio API', 'This browser does not support the Web Audio API'], ['瀏覽器不支援離線重取樣', 'This browser does not support offline resampling'], ['MP3 編碼器尚未載入', 'The MP3 encoder has not loaded'], ['OGG 編碼器尚未載入', 'The OGG encoder has not loaded'], ['正在本地重取樣與編碼…', 'Resampling and encoding locally…'], ['轉換完成，可以播放或下載輸出檔。', 'Conversion complete. Play or download the output.'], ['音訊轉換失敗：', 'Audio conversion failed: '],
        ['即時色碼互轉', 'Live color conversion'], ['編輯任一欄位，其他格式會即時同步。', 'Edit any field and the other formats update instantly.'], ['選擇色彩', 'Choose a color'], ['複製 CSS', 'Copy CSS'], ['複製全部色碼', 'Copy all color codes'], ['重設', 'Reset'], ['色彩已準備完成。', 'Color is ready.'], ['色彩已同步為 ', 'Color synced to '], ['色碼已複製到剪貼簿。', 'Color codes copied to clipboard.'], ['已重設為預設色彩。', 'Reset to the default color.'], ['格式無法解析，請確認色碼內容。', 'Format could not be parsed. Check the color value.'], ['圖片調色盤提取', 'Extract a palette from an image'], ['從本地圖片取樣主要色彩，適合快速建立品牌或介面配色。', 'Sample dominant colors from a local image to build a brand or interface palette.'], ['Canvas 會在瀏覽器本地取樣，不上傳圖片', 'Canvas samples locally in the browser; the image is not uploaded'], ['調色盤 CSS', 'Palette CSS'], ['複製調色盤', 'Copy palette'], ['取樣方式', 'Sampling method'], ['調色盤會縮小圖片並以色彩分桶統計，提供 5–8 個常見顏色作為起點。', 'The palette downscales the image and buckets colors, returning 5–8 common colors as a starting point.'], ['色碼與圖片只經過 JavaScript、Canvas 與 File API，不會離開你的裝置。', 'Color codes and images use only JavaScript, Canvas and the File API; they never leave your device.'], ['已從圖片提取 ', 'Extracted '], [' 個主要色彩。', ' dominant colors from the image.'], ['圖片無法讀取，請重新選擇。', 'The image could not be read. Please choose it again.'],
        ['本專區工具均以瀏覽器本地處理為設計原則；實際可處理速度仍會受裝置效能、瀏覽器與檔案格式影響。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'These tools are designed for browser-local processing. Actual speed depends on your device, browser and file format. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理字幕。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes subtitles only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理影像。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes images only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理資料。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes data only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理圖片。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes images only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理 Base64 與 SVG。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes Base64 and SVG only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理音訊。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes audio only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'], ['本工具只在瀏覽器本地處理色碼與圖片。Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'This tool processes color codes and images only in your browser. Amazon, TradingView and Ko-fi links may include partner tracking.'],
        ['Amazon、TradingView 與 Ko-fi 連結可能包含合作推廣標記。', 'Amazon, TradingView and Ko-fi links may include partner tracking.'], ['資料整理', 'Data'], ['文件工作流', 'Document workflow'], ['Web Audio', 'Web Audio'], ['Canvas', 'Canvas'], ['SheetJS', 'SheetJS'], ['jsPDF', 'jsPDF']
    ];

    function translate(value) {
        var output = String(value == null ? '' : value);
        pairs.forEach(function (pair) { output = output.split(pair[0]).join(pair[1]); });
        return output;
    }

    var originalStatus = C.setStatus;
    C.setStatus = function (element, message, kind) { return originalStatus(element, translate(message), kind); };
    var originalFileInfo = C.renderFileInfo;
    C.renderFileInfo = function (element, file, extraRows) {
        var rows = (extraRows || []).map(function (row) { return [translate(row[0]), row[1]]; });
        return originalFileInfo(element, file, rows);
    };

    function translateNode(node) {
        if (node.nodeType === 3) {
            var next = translate(node.nodeValue);
            if (next !== node.nodeValue) node.nodeValue = next;
        } else if (node.nodeType === 1) {
            ['placeholder', 'aria-label', 'title'].forEach(function (attribute) {
                if (node.hasAttribute(attribute)) node.setAttribute(attribute, translate(node.getAttribute(attribute)));
            });
            Array.from(node.childNodes).forEach(translateNode);
        }
    }

    function boot() {
        document.title = translate(document.title);
        var description = document.querySelector('meta[name="description"]');
        if (description) description.setAttribute('content', translate(description.getAttribute('content')));
        translateNode(document.body);
        var observer = new MutationObserver(function (records) { records.forEach(function (record) { Array.from(record.addedNodes).forEach(translateNode); }); });
        observer.observe(document.body, { childList: true, subtree: true });
    }
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
}());
